### ISSUE TITLE
Rename lightbulb

### ISSUE THREAD

**Issue by samreid** [phetsims/griddle#1]
Lightbulb as a project name doesn't seem too appealing.  Can we come up with a better name for our charting library?

**Comment by jbphet** [comment]
How about "tuft" as a nod to Edward Tufte, author of well-known "The Visual Presentation of Quantitative Information".  Or even Tufte.  Other ideas: "compass", or "marinus", who was a Greek cartographer (i.e. chart maker).

**Comment by samreid** [comment]
At today's meeting, someone suggested "deschartes"--in my opinion a nice wordplay but too tricky if you only see it written.  I also heard the suggestion "uncharted"

**Comment by samreid** [comment]
How about `chartology`?

**Comment by pixelzoom** [comment]
I like `graphet`, but it's already taken: http://www.graphet.com

**Comment by samreid** [comment]
Graphite?

**Comment by pixelzoom** [comment]
http://graphite.wikidot.com

**Comment by samreid** [comment]
Do you foresee issues in using an "already taken" name?  We do have some precedent for this, good or bad:

Kite: A Data API for Hadoop
http://kitesdk.org/docs/current/

DOT 2.0: Macromolecular Docking Software
http://www.sdsc.edu/CCMS/DOT/

Joist: Estimate, Invoice, & Manage On The Go 
https://www.joistapp.com/

etc. etc.

**Comment by pixelzoom** [comment]
No problem with a taken name when it's used for something different. Eg, PhET's 'kite' has nothing to do with Hadoop. graphite, on the other hand, is an established (2006) graphing tool, used by many large companies (http://graphite.readthedocs.org/en/latest/who-is-using.html). Why would we want to create another graphing library with the same name?

**Comment by pixelzoom** [comment]
How about griddle?

**Comment by pixelzoom** [comment]
griddle
chartreuse (chart reuse)
gridiron
gridlock
ingrid (in grid)
axis (bold as love)

**Comment by samreid** [comment]
> Why would we want to create another graphing library with the same name?

Agreed.  I'll create a new issue comment that summarizes the ideas so far, and has columns for votes (on a scale of 1-10), in case that helps.

**Comment by samreid** [comment]
Here are my votes on the current proposals:

| name | Sam |
| --- | --- |
| lightbulb | 1 |
| tuft | 1 |
| compass | 2 |
| marinus | 3 |
| deschartes | 2 |
| uncharted | 2 |
| chartology | 8 |
| griddle | 6 |
| chartreuse | 7 |
| gridiron | 5 |
| gridlock | 5 |
| ingrid | 3 |
| axis | 1 |

**Comment by samreid** [comment]
Today we agreed on griddle.  Reassigning to @jbphet for the renaming.

**Comment by jbphet** [comment]
Renaming complete, tested in Neuron and it worked fine.  Closing.
