### ISSUE TITLE
screenView step is expensive

### ISSUE THREAD

**Issue by TheDataLeek** [phetsims/griddle#13]
Currently as far as I can tell the `screenView.step` functionality tries to create a new frame as soon as it finishes the previous frame. This is expensive is resources and can cause slowdowns. Either some timestep duration needs to be implemented, or we can use javascript's `setInterval` method. Here's an hack using `griddle-main.js` that is much less resource intensive by drawing a frame every 10ms:

```
function step() {
    series.addPoint( time, -Math.abs( -Math.sin( time / 100 + count ) * 400 * 0.8 ) );
    time = time + (forward ? 1 : -1);

    if ( time > 400 ) {
        forward = false;
        count++;
    }
    if ( time < 0 ) {
        forward = true;
        count++;
    }
};

var frame_id = setInterval(step, 10);
```

**Comment by samreid** [comment]
screenView.step is actually running from requestAnimationFrame rather than setInterval, which is attempting to get 60fps on our platforms.  If you don't want data points added every frame, you could just do something like:

``` js
count++;
if (count%6===0){return;}
```

**Comment by pixelzoom** [comment]
@samreid's proposed solution above seems reasonable.  And no one has worked on this for 3+ years.  So closing as "won't fix".
