### ISSUE TITLE
add XYPlot.removeSeries

### ISSUE THREAD

**Issue by samreid** [phetsims/griddle#14]
See https://github.com/phetsims/griddle/pull/12

**Comment by samreid** [comment]
Here's what I envisioned for XYPlot.removeDataSeries (see commit above).  I tested it out by adding this snippet into the first line of screenView.step() in griddle-main.js

``` js
            if ( time > 100 ) {
              plot.removeSeries( series );
              screenView.step = function() {};
            }
```

**Comment by TheDataLeek** [comment]
This looks good and definitely works. Way simpler than what I was doing. This satisfies #12's purpose. Adding comment in #12 as well.

**Comment by samreid** [comment]
Perfect, thanks!  Closing.
