### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by jbphet** [phetsims/griddle#2]
The code in this repository should be reviewed, since it has been used in the Neuron sim, which is due to be released fairly soon.

**Comment by pixelzoom** [comment]
@ariel-phet Since this code review is 3+ years ago, I'm inclined to close this issue.  You thoughts?

**Comment by pixelzoom** [comment]
At the time that this issue was opened, "The code in this repository" refers to XYDataSeries, XYDataSeriesNode, and XYPlot.  (This is based on git history.)

**Comment by pixelzoom** [comment]
There's only 1 open issue related to this code review (#4), so I'm going to close this issue.
