### ISSUE TITLE
Additional functions to verticalBarChart.js

### ISSUE THREAD

**Issue by Denz1994** [phetsims/griddle#25]
We should look into adding more functions to verticalBarNode.js

Thoughts:

- [ ] changeColor(): changes the fill of the verticalBarNode
- [ ] addOneBar(): add a bar to the chart
- [ ] removeBars(): remove a bar from the chart
- [ ] addBarGroup(): add a group of bars to the chart

**Comment by pixelzoom** [comment]
@Denz1994 verticalBarNode.js no longer exists. Is this issue still relevant? Can it be closed? Or should the title be changed?

**Comment by Denz1994** [comment]
Good catch @pixelzoom. Closing this issue.
