### ISSUE TITLE
Use VSlider for the bar chart demo

### ISSUE THREAD

**Issue by samreid** [phetsims/griddle#28]
In https://github.com/phetsims/wave-interference/issues/111#issuecomment-418533154 @pixelzoom said:

> The griddle BarChart demo looks like an excellent opportunity to use VSlider, since the sliders control bar height.   Currently:

![screenshot_746](https://user-images.githubusercontent.com/3046552/45060207-3c4d9f80-b05c-11e8-9a4d-e390a6fc87e9.png)

I replied

> The HSliders were introduced in https://github.com/phetsims/griddle/commit/6f1477b5831fae95996ffa7c0d4b26df76c0c5d1, I'll create a griddle issue.

**Comment by samreid** [comment]
Not sure who to assign this to.  Maybe @zepumph could convert these as part of his review?

**Comment by pixelzoom** [comment]
I'll do it.

**Comment by pixelzoom** [comment]
VSliders with color-coded tracks (which is a lot easier than color-coded thumbs):

![screenshot_747](https://user-images.githubusercontent.com/3046552/45060951-88e6aa00-b05f-11e8-952c-a2b398b0dd33.png)

Back to @samreid for review.

**Comment by zepumph** [comment]
Thank you @pixelzoom.

**Comment by samreid** [comment]
Change set looks good, runtime looks good, thanks, closing.
