### ISSUE TITLE
BarChartNode TODOs and dead code

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/griddle#29]
`BarChartNode` has multiple TODOs without associated GitHub issues, and a bit of dead code.

```js
6   * TODO: Add horizontal support
96           maxWidth: 40 // TODO: Standardize
98        // barLabelVBox.addChild( labelText );
```

**Comment by Denz1994** [comment]
As part of https://github.com/phetsims/tasks/issues/1017:
The header documentation has been edited to note that `BarChartNode` is vertically aligned. There is no motive to add horizontal support at this moment. If horizontal support is needed it should be addressed in a specific issue.

The dead code above was removed at some point.
