### ISSUE TITLE
Change griddle to support custom layering?

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/griddle#32]
In https://github.com/phetsims/energy-skate-park/issues/31 we thought about using griddle for the bar graph in energy-skate-park. But the bar graph in energy-skate-park requires very custom layering and rendering with webgl to remain fast on ipads and keep a lower memory profile. EnergySkateParkScreenView is structured like this for rendering:
```
bottom layer of svg nodes
middle layer of WebGL nodes (if possible)
top layer of svg nodes
```
to reduce the number of canvas elements for webgl. So the graph in EnergySkatePark is broken up into a background layer (BarGraphBackground) with buttons, axis, labels, offscale arrows, and so on. And a foreground layer with the bars as rectangles using `renderer: webgl`. And we might even need to move the labels to a new layer on top so they can be seen when the bar represents negative values like in https://github.com/phetsims/energy-skate-park/issues/25#issuecomment-432714812. In order to use griddle in energy-skate-park, we would need to split up griddle components in a similar way. BarChartNode would still compose everything for convenience, but components could be layered if necessary for cases like energy-skate-park.

Is there a better way to do this? Does this seem worthwhile, or should we just continue to not use griddle in energy-skate-park? Benefit is that sims like energy-skate-park that need this performance optimization could use it. But it really complicates griddle code and will take more time to change.

@Denz1994 @jonathanolson do you have any thoughts?

**Comment by jessegreenberg** [comment]
I am leaning toward not using griddle in energy-skate-park due to the added complexity unless others think it will be required in other places in the future.

**Comment by Denz1994** [comment]
Just adding to the brainstorming. It seems like the only benefit for introducing layers is to support a set of components with a specific renderer and z-ordering.

If we added support for these layers we could have sim code determine what graph components should be in each layer and what renderer is used via options. Each layer is passed in with a specific set of components and renderer.
```js
    new BarChartNode( bars, rangeProperty, {
        layering: [
          { components: [ xAxisNode, yAxisNode, labelNode ], renderer: 'webGL' },
          { components: [ bars ], renderer: 'svg' },
          { components: [ labels  ], renderer: 'webGL' }
        ]
      } )
} )
```
The above psuedo-code follows a type structure with a few considerations:
```js
 array.[{array.[Node], string}]
```
- Fault tolarance should be added to assure that if this `layering` option is defined, then all components should be included. Alternatively, excluded components should be ammended to an additional layer.

- Internal components (axises, bars, labels) would need to be passed into the options. Perhaps MutableOptionsNode could be used here, but I'm not sure. I don't think we want the client to pass in sim generated components.

**Comment by Denz1994** [comment]
Another suggestion involves removing flexibility by choosing a specific rendering configuration for performance, via an option.

```js
    new BarChartNode( bars, rangeProperty, {
        renderingLayout1: true
} )
```
With this flag set to true, specific layers are configured with the appropriate renderer. The configuration of layer components and renderers that worked for ESP, could be applied here. Any performance enhancements made from this specific layout in ESP may be transposed to other sims and worth reusing. There is a maintainability issue here because everytime a new layout is needed for improved performance in another sim, a new `rederingLayout2` option would have to be added (similar to `NumberControl.layoutFunction`).

**Comment by jonathanolson** [comment]
This sounds relevant to arbitrary types of components in general, not just for griddle.

We could potentially have certain components support re-parenting of certain children? For example, you'd document something as `// @public {Node} (re-parentable)`, and that would make the guarantee that, as long as the parents for the main node (and all re-parentable children) were the same, that it would look correct.

This is more general, assigning to the dev meeting to see if this idea is too crazy in general.

**Comment by samreid** [comment]
I'm not opposed to generalizing common code components for reparenting, as long as it is not too complicated or unmaintainable, but if we are dropping support for iPad2, then maybe sims like Energy Skate Park: Basics will no longer need hacks like it used to.

**Comment by jessegreenberg** [comment]
Thanks for brainstorming @Denz1994. I still think this would overly complicate griddle for something that will likely only be useful in ESP. If similar rendering/layering requirements show up in a second sim that uses griddle then maybe that would be a good time work on this more.

**Comment by pixelzoom** [comment]
Am I understanding from this issue that griddle uses WebGL to render bar graphs?  My understanding (from the README.md) is that griddle is supposed to be a charting package based on scenery, usable by all sims.  And I don't think that WebGL should be a required part of something as simple as a bar graph.  If that's an ESP:B requirement for performance, then it doesn't belong in griddle.

**Comment by samreid** [comment]
To summarize this issue: griddle does not currently support WebGL or even breaking out components so they can be in a dedicated WebGL layer.  The question for this issue is whether we should add support for that one way or another.

Additionally, perhaps we should decide on https://github.com/phetsims/energy-skate-park/issues/42 before deciding this issue.

**Comment by jessegreenberg** [comment]
In https://github.com/phetsims/energy-skate-park/issues/40, the bars got even more complicated/different from griddle to support a stroked rectangle with webgl, and the layering needed to make the labels visible under semi-transparent bars.

If we proceed with https://github.com/phetsims/energy-skate-park/issues/42 (removing WebGL from the sim) then we can use griddle as is.

I am going to go ahead and close this issue, I don't think it would be beneficial for griddle or make energy-skate-park more maintainable.

@jonathanolson posed a question to the dev group in https://github.com/phetsims/griddle/issues/32#issuecomment-434942277, Ill make a new issue for that.
