### ISSUE TITLE
Add ability to hide BarNodes in BarChartNode

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/griddle#35]
Energy Skate Park is now using griddle. One of the requirements is that the bars be completely hidden if the values are small enough, and so the custom graph that was used in that sim had
```js

        // Floor and protect against duplicates.
        // Make sure that nonzero values
        // For thermal and total energy, make sure they are big enough to be visible, see #307
        // For kinetic and potential, they must go to zero at the endpoints to reach learning goals like
        //   "The kinetic energy is zero at the top of the trajectory (turning point)
        var smallValueThreshold = showSmallValuesAsZero ? 1 : 1E-6;
        var answer = absResult > 1 ? Math.floor( result ) :
                     absResult < smallValueThreshold ? 0 :
                     1;
```
(where `answer` set the height of the bar).

@Denz1994 @jonathanolson can we add similar functionality to griddle? I am wondering about adding an entry to BarChartNode `entries` that looks like this:

```js
   // [showBar]: {Function} @returns {boolean} - Called on update(), if function returns false, the bar is made invisible
```

**Comment by Denz1994** [comment]
Perhaps we can get away with extending what is considered an "invalid bar" in `BarNode.js`. Currently, an invalid bar is one with a negative energy value and does so by checking against the scaled value of the bar. These invalid bars only trigger a flag called hasNegative.

We could additionally, make a bar invalid if its value is below a threshold and just make it invisible at that point.

It would require adding an option and condition resembling:
```js
  @private {number}
  this.smallValueThreshold = options.smallValueThreshold
  ... 


  ...
   // Check for whether we have an "invalid bar" case with the total and hasNegative
      for ( i = 0; i < this.barEntries.length; i++ ) {
        var value = this.barEntries[ i ].property.value * scale;
        if ( value < 0 ) {
          hasNegative = true;
        }
        total += value;
        
      if ( options.smallValueThreshold ) {

          // Don't show small values beyond the threshold
          this.visible = Math.abs(total) > this.smallValueThreshold
        }
      }
```

Here `smallValueThreshold` is a number we can pass into options so we don't need an additional function during every update(), which typically gets called on step().

**Comment by jessegreenberg** [comment]
It looks like the current implementation of "invalid" would change the bar colors, and this seems like a slightly different usage to me.

What I like about the arbitrary function is that is is general and a bar can be hidden for any reason. But it is more complicated and maybe we will never need this.

But I am also OK with an option like `smallValueThreshold`. For energy-skate-park different bars need different values, so it would still need to be defined on each bar entry.

@Denz1994 do you have a preference between these?

**Comment by Denz1994** [comment]
> But it is more complicated and maybe we will never need this.

I would opt for the `smallValueThreshold` option because it seems like less overhead and gives us the flag we need to manage visibility.

**Comment by jessegreenberg** [comment]
Ok, thanks for the consult, I will go ahead with that.

**Comment by jessegreenberg** [comment]
Hmm, well I misinterpreted what I needed in ESP. What I actually need is more complicated. For two of the bars, we need to say if the value is less than some threshold, show zero. For the other two bars I need to say, if the value is greater than thresholdA and less than thressholdB, show some minimum height. This can either be accomplished with 3 different options or a single callback like `modifyBarHeight`. I will try the callback, it seems like it could be better than adding 3 options to BarNode entries for this.

**Comment by jessegreenberg** [comment]
This is actually pretty clear and working well now in ESP. @Denz1994 what do you think of the above commits?

Alternatively, we could add the following to  barEntries:
`smallValueThreshold`
`smallValueRange`

and then assert that smallValueThreshold is less than smallValueRange.min (or that only one of these should be used at a time)? But I prefer this general function personally, I think in the future we may want to do more "hollywooding" of the bar heights in different ways.

**Comment by Denz1994** [comment]
It seems like we are on track for adding features that modify the scale of the bar in a variety of ways. In that case, we want to keep our options open. The function added as an option is appropriate.

I'm not sure why https://github.com/phetsims/griddle/commit/81951fa56e1db9afc464b26186ce7a749f102645 was changed it looks like the succeeding line overrides `currentY` value making it a no-op. @jessegreenberg could you verify?
```js
if ( barEntry.modifyBarHeight ) {
          currentY = barEntry.modifyBarHeight( barEntry.property.value, scale );
        }

        // Use only the first entry to display the effective range
        currentY = effectiveRange.constrainValue( total );
```

**Comment by Denz1994** [comment]
Now that I'm thinking about this, my most recent [comment](https://github.com/phetsims/griddle/issues/35#issuecomment-495173953) may explain this behavior I'm seeing.

(TE = Total Energy, PE = Potential Energy)
1. Open Bar Chart and set zoom to max (hit plus sign until disabled)
2. Drag the skater, making sure only TE and PE are being updated.
3. Drag skater down towards the ground very slightly.
4. When close enough to the ground the PE will display zero but the TE will have a small value.

![image](https://user-images.githubusercontent.com/13894380/58249281-6d761900-7d2c-11e9-9c2e-210922bce1f2.png)

The commit https://github.com/phetsims/griddle/commit/81951fa56e1db9afc464b26186ce7a749f102645 is relevant to the composite bar, while non-composite bars are working just fine.

 My best guess is either:

- Commit https://github.com/phetsims/griddle/commit/81951fa56e1db9afc464b26186ce7a749f102645 is preventing modified heights on composite bars

- Or the total bar in ESP should not show small values using `showSmallValues`.
```js
const totalEntry = { property: skater.totalEnergyProperty, color: EnergySkateParkColorScheme.totalEnergy, modifyBarHeight: showSmallValues };
 `modifyBarHeight: showSmallValues`
```

Thoughts @jessegreenberg ?

**Comment by Denz1994** [comment]
When you release the drag the thermal energy shows making the total energy make sense. Thermal energy isn't being removed from total energy when dragging.

If https://github.com/phetsims/griddle/issues/35#issuecomment-495173953 is a non-issue then the changes to BarChart are fine and my comments [here](https://github.com/phetsims/griddle/issues/35#issuecomment-495178606) should be moved to another ESP issue.

**Comment by jessegreenberg** [comment]
> Or the total bar in ESP should not show small values using showSmallValues

I suspect this to be the case, but I will check with the published sim. The bars in ESP are non-composite so I don't think that https://github.com/phetsims/griddle/commit/81951fa56e1db9afc464b26186ce7a749f102645 is related.

**Comment by jessegreenberg** [comment]
For https://github.com/phetsims/griddle/issues/35#issuecomment-495173953, I wanted the height to still be constrained to the range which is why `modifyBarHeight` is followed by `constrainValue` for both cases.

**Comment by jessegreenberg** [comment]
Regarding https://github.com/phetsims/griddle/issues/35#issuecomment-495290029 this is happening in the published sim, it is the result of forcing the PE bar to zero. It is made much more apparent by zooming way in as you pointed out @Denz1994.

![image](https://user-images.githubusercontent.com/6396244/58270109-0883e880-7d57-11e9-9c52-729b57310db3.png)

**Comment by jessegreenberg** [comment]
@Denz1994 since this is a sim behavior I will move to ESP. What do you think of https://github.com/phetsims/griddle/issues/35#issuecomment-495291719 and are there still issues?

**Comment by Denz1994** [comment]
Thanks for the clarification. I don't see an issue with your changes to BarChartNode. This looks good.

I didn't know that the ESP specific point was in the published version. I'll leave it to you to determine the next steps for the observation mentioned. It may not be worth additional time to patch, but I'll defer to you.

**Comment by jessegreenberg** [comment]
OK, thanks @Denz1994, it will ultimately be a design decision in ESP I think, I will run it by the design team. Thanks for the review, going to close this issue.
