### ISSUE TITLE
Add way to get positioning of BarNodes from BarChartNode

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/griddle#37]
In Energy Skate Park, we need to position a button under underneath one of a BarNode label like https://user-images.githubusercontent.com/8419308/47312442-98af5300-d5f9-11e8-8c1b-dc79fa96c786.png

It would be helpful to be able to get the positions of bars and labels.

**Comment by jessegreenberg** [comment]
I added getBarLabelLocation to BarChartNode for this. @Denz1994 would you mind reviewing this?

**Comment by Denz1994** [comment]
Just out of curiosity, why wouldn't specifying the `labelNode` not work in this case?

```js
this.barChart =new BarChartNode( [ {
        entries: [ barEntry ],
        labelString: barLabelString,
        labelNode: TrashCanButtonNode // or TrashCanButtonVBox for added VStrut padding
      }, rangeProperty, options);
```

 I'm looking at `BarChartNode.js`:
```js
   if ( bar.labelNode ) {
        barLabelVBox.addChild( bar.labelNode );
      }
```

Or do we need more flexibility in where the node is placed?

**Comment by jessegreenberg** [comment]
Oh my gosh I totally missed this, sorry! Ill give that a try instead.

**Comment by jessegreenberg** [comment]
That works beautifully, thanks @Denz1994. I am just going to remove my changes for this issue.

**Comment by jessegreenberg** [comment]
Removed.
