### ISSUE TITLE
Add option for font of y ticks for XYPlot

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/griddle#38]
I would like to adjust the font of the y tick labels of XYPlot like you can with the tick labels along the x axis. It seems like tickLabelFont could be applied to both x tick labels and y tick labels, or we could have independent options for each, `xTickLabelFont` and `yTickLabelFont`. 

@samreid is listed as the author of XYPlot, so passing the question to him, do you have a preference?

**Comment by jessegreenberg** [comment]
The only other usage of XYPlot outside of demos is in ProteinLevelChartNode of gene-expression-essentials which has no Y labels with `showYAxisTickMarkLabels: false`, so we if we decide apply tickLabelFont to both it won't have an impact on existing sims.

**Comment by jessegreenberg** [comment]
I went with applying `tickLabelFont` to both x and y axes, @samreid could you please review?

**Comment by veillette** [comment]
That's a reasonable approach. Closing
