### ISSUE TITLE
Support negative values with XYDataSeriesNode

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/griddle#39]
XYDataSeriesNode plots relative to the bottom of the bounds rather than the y = 0 tick of the XYPlot. The result is if the range of the plot goes from y = -10 to y = 10,  data points with y = 0 will be drawn at the bottom of the plot around y = -10.

**Comment by jessegreenberg** [comment]
Proposed fix committed above.

**Comment by jessegreenberg** [comment]
Assigning to @samreid for review since he is listed as an author, but please let me know if you are unable to review at the moment.

**Comment by samreid** [comment]
I don't expect to have time to review this in the near future.

**Comment by jessegreenberg** [comment]
OK, understood. @ariel-phet could you please recommend another reviewer for griddle for this issue and #38?

**Comment by ariel-phet** [comment]
@veillette said he is happy to do this review

**Comment by veillette** [comment]
@jessegreenberg, I reviewed your work to support to negative values.  Good work. Closing
