### ISSUE TITLE
XYDataSeries, XYDataSeriesNode, XYPlot do not meet code standards

### ISSUE THREAD

**Issue by jbphet** [phetsims/griddle#4]
There isn't much documentation in this code.  For instance, XYDataSeriesNode has no header comment at all.  XYDataSeries has a header comment that says, "XY Data Series", which isn't very useful. There are a number of public methods with no documentation.  Documentation needs to be added pretty much everywhere. This was noted during code review, see #2.

**Comment by pixelzoom** [comment]
At the time that this issue was opened, "this code" referred to XYDataSeries, XYDataSeriesNode, and XYPlot.  (This is based on git history.)

**Comment by pixelzoom** [comment]
XYDataSeries, XYDataSeriesNode, and XYPlot still don't meet PhET code standards. Specifically:

- no visibility annotations for fields
- no visibility annotations for methods
- insufficient header documentation, should give an overview of features/responsibilities

**Comment by samreid** [comment]
I believe those types are now called DynamicSeries, DynamicSeriesNode and XYChartNode.  In other issues, some of the visibility annotations were added.  However, I recommend deprecating these types and using bamboo for future development.  @pixelzoom can this issue be closed?

**Comment by pixelzoom** [comment]
Agreed, no reason to spend time on deprecated code. Closing.
