### ISSUE TITLE
XYPlot labels assume minY is less than or equal to zero

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/griddle#40]
Related to #39, the labels look good if the range extends from a minY of less than or equal to zero, but if minY is greater than zero, the bottom of the graph is incorrectly labelled. Here is a plot with minY of 1000:
![image](https://user-images.githubusercontent.com/6396244/58995313-f3747400-87b0-11e9-8e0c-065181b307d0.png)

**Comment by jessegreenberg** [comment]
It is because of this correction.
```js
    // horizontal grid lines
    // if minY and maxY is not a multiple of step function convert them to multiples
    this.minY = options.minY;
    if ( this.minY % options.stepY !== 0 ) {
      this.minY = Math.floor( this.minY / options.stepY ) * options.stepY;
    }
    this.maxY = options.maxY;
    if ( this.maxY % options.stepY !== 0 ) {
      this.maxY = Math.ceil( this.maxY / options.stepY ) * options.stepY;
    }
```

**Comment by jessegreenberg** [comment]
These are probably here so that the grid lines divide the graph evenly, but that is not the behavior I would expect when providing a given minY, maxY, and stepY. If I remove those lines the graph looks like this, which is more correct in my opinion.

![image](https://user-images.githubusercontent.com/6396244/58996156-3a179d80-87b4-11e9-8bdf-fb7f473ed4a0.png)

But they may be important to keep for reasons I haven't thought of. Assigning the question to @samreid since he is the listed author, but please reassign if that is't correct or you don't have time to review.

**Comment by samreid** [comment]
Showing the correct `minY` sounds great.  The latter chart seems like we shouldn't show the `12000` because it doesn't match the interval or have a gridline.  But I'm not 100% sure.

**Comment by jessegreenberg** [comment]
> The latter chart seems like we shouldn't show the 12000 because it doesn't match the interval or have a gridline.

Oh, very good point, I agree.

**Comment by jessegreenberg** [comment]
Hmm, thinking about it more I am actually not as sure either. @amanda-phet do you have an opinion about this? Should the chart in https://github.com/phetsims/griddle/issues/40#issuecomment-499288549 show the 12000 label since the grid lines are spaced at intervals of 4000?

**Comment by amanda-phet** [comment]
What is this graph for? The y-axis in https://github.com/phetsims/griddle/issues/40#issuecomment-499288549 looks really strange to me, but if it is to scale then it's not incorrect. 

The best thing to do is probably include a break in the graph. Both axes will start at 0, but if you see a visible break that helps to orient the viewer. Then include a line at the minimum value (1000) and lines increasing by a set value (every 4000 or whatever). 

Does that help?

**Comment by jessegreenberg** [comment]
Thanks @amanda-phet that does help! I was working on energy-skate-park but a range like this isn't used anywhere yet, I just discovered that the graph is drawn incorrectly if minY starts at something greater than zero. Adding a break towards the bottom makes a lot of sense. 

How about the top of the graph, in general should "12000" be displayed? The grid is separated by "4000" , the next grid line would have been at "13000".

**Comment by samreid** [comment]
It seems best to answer these questions in sim-specific contexts if/when it comes up, let's close this more general issue.
