### ISSUE TITLE
New way to map XYDataSeries -> XYDataSeriesNode in XYPlot

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/griddle#41]
The seriesViewMap of XYPlot is trying to map XYDataSeries to XYDataSeriesNodes but Javascript objects cannot map objects to objects. We need a different way to form the map or a different way to get references to XYDataSeriesNodes.

**Comment by jessegreenberg** [comment]
This would be trivial if we could use Map (https://github.com/phetsims/tasks/issues/992) but we could also attach a unique key to each XYDataSeries instance for lookup instead until we know that Map is usable.

**Comment by samreid** [comment]
The current implementation uses `{}` with object keys--I'm not sure if that is working.  Have you considered something like this?

```
Index: js/XYPlot.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/XYPlot.js	(revision f76105e1b909ee5619aabe41dbcbf2dfc92a4ebe)
+++ js/XYPlot.js	(date 1559792783000)
@@ -158,15 +158,7 @@
     } ) );
 
     this.addChild( content );
-
-    /**
-     * Map XYDataSeries -> XYDataSeriesNode
-     * @public
-     * @type {{}}
-     */
-    this.seriesViewMap = {};
     this.content = content;
-
     this.mutate( options );
   }
 
@@ -180,11 +172,10 @@
      * @param {boolean} scaleFactor
      */
     addSeries: function( series, scaleFactor ) {
-      this.seriesViewMap[ series ] = new XYDataSeriesNode( series, this.rectangle.bounds, {
+      this.content.addChild( new XYDataSeriesNode( series, this.rectangle.bounds, {
         xScaleFactor: scaleFactor ? this.xScaleFactor : 1,
         yScaleFactor: scaleFactor ? -this.yScaleFactor : 1
-      } );
-      this.content.addChild( this.seriesViewMap[ series ] );
+      } ) );
     },
 
     /**
@@ -192,10 +183,9 @@
      * @param {XYDataSeries} series
      */
     removeSeries: function( series ) {
-      var view = this.seriesViewMap[ series ];
-      this.content.removeChild( view );
-      view.dispose();
-      delete this.seriesViewMap[ series ];
+      this.children
+        .filter( child => child instanceof XYDataSeriesNode && child.series === series )
+        .forEach( child => this.content.dispose() );
     }
   } );
 } );
\ No newline at end of file
```

This eliminates the extra tracking data structure and just uses children and filtering, and relies on dispose for also doing detach.  It is O(N) instead of O(1) but since we are typically showing less than 1000 data series, this may be acceptable.

**Comment by jessegreenberg** [comment]
Thanks for taking a look! No it is not working currently, and the above could work for disposal. But in energy-skate-park I need to access individual XYDataSeriesNodes so that they can be made visible/invisible from user controls. My guess is public access to these Nodes was the original intent of the map since it is marked as `@public`.

**Comment by jessegreenberg** [comment]
I changed the map so that it goes from XYDataSeries.uniqueId -> XYDataSeriesNode for now, we can remove the unique ID on XYDataSeries when we can use Map.

**Comment by jessegreenberg** [comment]
I promoted this to a TODO in the code that references https://github.com/phetsims/tasks/issues/992 so that this can be changed when Map is supported. This issue can be closed now that XYDataSeriesNodes can be retrieved from the public object.
