### ISSUE TITLE
Add ability to zoom in/out of XYPlot

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/griddle#44]
I need this for energy-skate-park, there currently isn't a way to zoom in on an XYPlot.

**Comment by jessegreenberg** [comment]
BarNode from BarChartNode uses scaleProperty, I might do something similar. But this time the scale should apply to the entire chart rather than just the bar.

**Comment by jessegreenberg** [comment]
Alternatively, one could set minX, maxX, minY, maxY, stepX, stepY dynamically.

**Comment by samreid** [comment]
For Circuit Construction Kit: AC, I'll need to add zoom in/out buttons for the scrolling chart node.  Not sure how much they will overlap with XYPlot zoom buttons.

**Comment by samreid** [comment]
@jessegreenberg is this feature necessary for Energy Skate Park?  What is the design?  I'm working on a related feature for CCK.

**Comment by jessegreenberg** [comment]
This is a feature of ScrollingChartNode, and XYPlotNode is deprecated. Closing.
