### ISSUE TITLE
Add a scatter plot

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/griddle#45]
In energy-skate-park we will need a scatter plot that will look something like this:
![image](https://user-images.githubusercontent.com/6396244/60113553-00490f80-9740-11e9-95b8-4cdb5e26344e.png)

And it should be added to griddle.

Like XYPlot, data will be added and removed through XYDataSeries.  Portions of XYPlot will be reused by this so I think we could do this one of two ways: 
We could create a super class like XYPlot that is extended by XYLinePlot (what is currently implemented by XYPlot) and XYScatterPlot for the scatter portion. Or we could just keep everything in XYPlot and have an option for line vs scatter drawing.

I am leaning towards the latter option now.

**Comment by jessegreenberg** [comment]
The second option is also nice because then a single XYPlot can change how it is displayed. We could have a setPlotStyle method that sets scatter vs line.

**Comment by jessegreenberg** [comment]
Next, we need the ability for points to fade out in energy-skate-park. This won't be straight forward because we don't have access to individual points which are drawn on the canvas.

This could be done by creating a new array in XYDataSeries like `pointOpacities`, with values at indices that match points in `xPoints` and `yPoints`. This gets added optionally on addPoint.

It could be made more general by making the array `pointStyle` or something which could directly control point color, visibility, maybe stroke, or size, or other things. I like this best, maybe in the future we will have a scatter plot where every 10th point needs to be larger thn the others.

**Comment by jessegreenberg** [comment]
An initial commit for this was done above, it is working well. So far only opacity is supported but now other things can be added.

**Comment by jessegreenberg** [comment]
Above commit finishes this. A new type called PointStyle was added to support this customization, it is being used in energy-skate-park now.

**Comment by samreid** [comment]
This was added to griddle in 2019 and is in usage in Energy Skate Park and in the Griddle demo.  Closing for now, we can reopen or create a new issue if there is more work to do.
