### ISSUE TITLE
Decimal places dependent on zoom level?

### ISSUE THREAD

**Issue by Denz1994** [phetsims/griddle#47]
Opening this issue to track progress on , as a part of  during https://github.com/phetsims/tasks/issues/1017
```
// TODO: Should the number of decimal places depend on the value or perhaps on zoom level?
  We want to show -2 -1 0 1 2, but also -0.5, 0, 0.5, right?
```
It seems like the motive here is that zooming in/out on a graph should update the number of decimal places. I will leave for a designer to detail specifics for the desired behavior or if we still want this behavior at all.

**Comment by arouinfar** [comment]
@Denz1994 I think it really depends on the range of values. If the range is large, we will likely need to support varying the number of decimal places with the zoom level. I think the specifics will always depend on the sim, so I'm not sure what the general solution would be.

**Comment by samreid** [comment]
For charts that require this level of flexibility, it may be easier to use bamboo.

**Comment by jonathanolson** [comment]
Closing, we don't need to support this (bamboo handles it).
