### ISSUE TITLE
Make it possible to set color of text labels on BarChartNode

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/griddle#49]
They currently match the color of the bar only.

**Comment by jessegreenberg** [comment]
This is done.  There is now an entry to the "bar" object called `labelColor` which can specify the color of the label. The default is now black, NOT the bar color. I went with this because in https://github.com/phetsims/energy-skate-park/issues/240 @arouinfar said
> I would be fine with doing this universally across all energy graphs. I suspect that the colors do not have sufficient contrast against light gray or white backgrounds to pass at the WCAG AAA level. https://webaim.org/resources/contrastchecker/

This would impact pendulum-lab and masses-and-springs. I kept the labels with their colors for now. @arouinfar can you confirm that the labels in these sims should be black?

**Comment by arouinfar** [comment]
@jessegreenberg yes, I think we should change the labels in pendulum-lab and masses-and-springs to black. In the graph, the text is right next to the bar so I don't think an extra level of color-cueing is necessary. These sims do have an energy legend that I think we'll need to make some design tweaks to, so I'll open an issue in the sim repos.

| Color | [Contrast Ratio Against White](https://webaim.org/resources/contrastchecker/) | Comments |
| --- | --- | --- |
| KINETIC_ENERGY `rgb( 30, 200, 45 )` | 2.24:1 | Fail |
| GRAVITATIONAL_POTENTIAL_ENERGY `rgb( 55, 130, 215 )` | 3.49:1 | Fails for normal text. Passes at AA level for large text. |
|  ELASTIC_POTENTIAL_ENERGY `rgb( 0, 204, 255 )` | 1.89:1 | Fail |
| HEAT_THERMAL_ENERGY `rgb( 255, 85, 0 )` | 3.2:1 | Fails for normal text. Passes at AA level for large text. |
| TOTAL_ENERGY `rgb(180, 180, 0)` | 2.21:1 | Fail |

**Comment by jessegreenberg** [comment]
OK thanks @arouinfar  - since you have made issues for the above two sims I think this issue can be closed.

**Comment by arouinfar** [comment]
@jessegreenberg I opened issues to fix the Energy Legend dialog which use the same colors as the bar graph labels, but I'd assumed the graph labels would be changed to black in this issue. Can you make this change, or should I open issues in the sim repos for that as well?

**Comment by jessegreenberg** [comment]
Ah sorry, I thought those issues included the change to the graphs as well. I can definitely do that here.

**Comment by jessegreenberg** [comment]
OK, labels have been made black. Anything else to do @arouinfar?

**Comment by arouinfar** [comment]
Looks good in master, thanks @jessegreenberg!
