### ISSUE TITLE
Grid lines on XYPlot are drawn using individual line nodes, which is expensive

### ISSUE THREAD

**Issue by jbphet** [phetsims/griddle#5]
The grid lines in the XYPlot are drawn using a set of Scenery Line nodes.  Since each one of these is a separate node, this is much more costly to draw than a single Path node.  This should probably be changed.

**Comment by jbphet** [comment]
This was found during code review, see #2.

**Comment by aadish** [comment]
similar to issue #8, closing this and tracking it in #8
