### ISSUE TITLE
XYPlot needs to be generalized

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/griddle#50]
I took another look at XYPlot, possibly for reuse in Natural Selection.  It's still has many problems that inhibit general use.

- [x] Recommended to rename XYPlot to XYPlotNode, to follow the convention used elsewhere in griddle (ScrollingPlotNode, XYDataSeriesNode,...)

- [x] Creating the grid and axes should also not be the responsibitites of this node, since a grid and axes are more general.  This now should use generalized grid and axes via composition. 

@samreid: In https://github.com/phetsims/griddle/issues/74 we will fix up the "plot" abstraction/naming.

- [x] XYPlotNodes look pretty rough where the axes join. There's a visible gap.  See screenshot below, from griddle demo. 

@samreid: Griddle no longer has a powerful axis node (aside from the one in bar chart).  I'll open a new issue for that.  https://github.com/phetsims/griddle/issues/85

- [x] Why are the default axes so heavy? Plotted data overlaps the axes.  See screenshot.

@samreid: this will be addressed in #85 

- [x] I don't see any support for major vs minor grid lines.  There's something called "intermediate lines", which is not at all typical of grids.  Major and minor ticks should have separate styling options.

@samreid: that was added in GridNode.

- [x] See also #4, #40, #44, #46 

@samreid: we will track those in their respective issues.

- [x] Highly recommended to have a look at JFreeChart's XYPlot (model and view) for API inspiration.

@samreid: The API is here: http://www.jfree.org/jfreechart/api/javadoc/org/jfree/chart/plot/XYPlot.html 

Assigning to @ariel-phet to prioritize and assign.

<img width="581" alt="screenshot_332" src="https://user-images.githubusercontent.com/3046552/82755573-a27ad880-9d91-11ea-9e29-0a5b927beaac.png">

**Comment by ariel-phet** [comment]
@jessegreenberg will look into making the simpler improvements in the near future

**Comment by jessegreenberg** [comment]
This is on hold, and we may just close this and invest in ScrollingChartNode instead, see #54.

**Comment by samreid** [comment]
All remaining work (other than reviewing JFreeChart plot APIs) is tracked elsewhere, and I took a scroll through http://www.jfree.org/jfreechart/api/javadoc/org/jfree/chart/plot/XYPlot.html and http://www.jfree.org/jfreechart/api/javadoc/org/jfree/data/xy/XYDataset.html, closing.
