### ISSUE TITLE
Incorrect comment?

### ISSUE THREAD

**Issue by jbphet** [phetsims/griddle#6]
The following code was found in XYPlot.  The comment doesn't seem to make sense in this context.  Cut and paste error?

``` js
    //tailX, tailY, tipX, tipY, options
    var panelOptions = {
      fill: this.options.backgroundFill,
      xMargin: 10,
      yMargin: 10
    };
```

**Comment by samreid** [comment]
Yes, that is likely.  Feel empowered to fix as much lightbulb as you wish!

**Comment by pixelzoom** [comment]
The bit of code reported in https://github.com/phetsims/griddle/issues/6#issue-56606955 no longer exists. Closing.
