### ISSUE TITLE
BarChartNode leaks memory

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/griddle#68]
BarChartNode adds 2 observers to param `rangeProperty` and never cleans them up. This is a memory leak.

**Comment by pixelzoom** [comment]
Memory leak fixed in the above commit by combining observers and overriding `dispose`. 

I also renamed `rangeProperty` to `yRangeProperty`, since BarChartNode has both `xAxis` and `yAxis`.

@Denz1994 would you mind reviewing?

**Comment by Denz1994** [comment]
Thanks for catching this memory leak. The dispose function added should have fixed this issue. Also, the refactoring of `yRangeProperty` is more specific to its purpose. Thanks for the changes. Closing this one.
