### ISSUE TITLE
delete deprecated classes in griddle?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/griddle#69]
Noted while working on https://github.com/phetsims/tasks/issues/1044.

XYPlotNode and XYDataSeriesNode are both annotated as `@deprecated`.  They are only used in the griddle demo.  Is there any reason not to delete them?

Unfortunately I noticed this after spending the time to convert XYDataSeriesNode to ES6.   Fortunately I noticed before converting XYPlotNode to ES6.

**Comment by samreid** [comment]
Yes, I'll delete them as part of https://github.com/phetsims/griddle/issues/63
