### ISSUE TITLE
XYPlot has two methods that do nothing

### ISSUE THREAD

**Issue by jbphet** [phetsims/griddle#7]
the `step` and `appendPoint` methods on the XYPlot type are empty.  Can they be removed?  If not, it should be clearly documented why they are there.

**Comment by pixelzoom** [comment]
Looks like someone removed `appendPoint`.  

`step` is still there, with comment "// Does nothing for now."

**Comment by pixelzoom** [comment]
I didn't see anything that uses XYPlot `step`, so I deleted it.  

Closing.
