### ISSUE TITLE
griddle uses incorrect/inconsistent terminology

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/griddle#71]
Noted in https://github.com/phetsims/griddle/issues/70#issuecomment-694426710 and relevant for https://github.com/phetsims/fourier-making-waves/issues/3:

> A bigger issue, throughout griddle and spilling over into sims, is terminology. I see "plot", "chart", and "graph" being used interchangeable. A plot is not a chart. A plot displays a data set (aka data series). A chart displays one or more plots. Names like XYCursorPlot and ESP.EnergyPlot are incorrect and misleading - they are charts, not plots. 

Assigning to @jessegreenberg and @samreid (the primary authors of griddle components) for discussion.

**Comment by pixelzoom** [comment]
For proper use of terminology, see hookes-law EnergyGraph, EnergyPlot, and XYPointPlot.

**Comment by jessegreenberg** [comment]
I do like the XY prefix. I am not aware of plans for 3D, but this is clear and leaves it open. The old XYPlotNode was removed. A more general issue was opened for renaming several things in Griddle I am going to move this over there.

**Comment by jessegreenberg** [comment]
Oops, I meant to put that comment in #63, reopening.

**Comment by jessegreenberg** [comment]
In #63 @pixelzoom said
> If griddle will only handle 2D data, then PlotNode is fine. If you think it might handle other dimensions, then it's not sufficiently descriptive - and neither is ScrollingChartNode, DynamicSeries, etc.

which is what https://github.com/phetsims/griddle/issues/71#issuecomment-696898597 comment was intended for.

Given that and 
> A plot displays a data set (aka data series). A chart displays one or more plots. 

I think the following renaming of things in griddle makes sense:
- Rename ScrollingChartNode -> XYPlotNode
- Rename XYCursorPlot -> XYCursorPlotNode
- BarChartNode ->XYBarChartNode (chart applies here, but it should also have the XY prefix)

**Comment by pixelzoom** [comment]
Those renames sound good.  But I think BarChartNode is fine as is -- I've never seen a bar chart that is anything other than 2D.  The Wikipedia entry on Bar Chart is pretty clear on the 2D nature, and even says "One axis of the chart shows the specific categories being compared, and the other axis represents a measured value."

**Comment by jessegreenberg** [comment]
Sounds good, I wasn't sure about that one. I went ahead with the rename of the others in https://github.com/phetsims/griddle/issues/71#issuecomment-696910040, including the one you mentioned in ESP.

Do you think there is anything else for this issue?

**Comment by jessegreenberg** [comment]
Should the ChartCursor (inner class of XYCursorPlotNode) be renamed to PlotCursor?

**Comment by pixelzoom** [comment]
Oh geeze, I'm so sorry... Those name changes in https://github.com/phetsims/griddle/issues/71#issuecomment-696906796 are _not_ correct. 

XYPlotNode is a chart, not a plot.  A chart is the grid + axes + plots --- the whole package. 

A plot is what's drawn on the chart - the rendering of one data set (e.g DynamicSeries).  

A chart should be able to draw multiple plots - this is what you're doing with `addDynamicSeries`.

So... 

XYPlotNode should be XYChartNode.  It is a chart that shows multiple plots, one for each DynamicSeries that has been added.

XYCursorPlotNode should be XYCursorChartNode.  It is a subclass of XYChartNode that adds a cursor.

griddle is currently missing the XYPlotNode piece of this puzzle.  Each DynamicsSeries should be rendered by an XYPlotNode on the XYChartNode.

If this still doesn't make sense, let's discuss.

**Comment by pixelzoom** [comment]
Back to @jessegreenberg for review. If the renames looks OK here, feel free to close.

**Comment by samreid** [comment]
@pixelzoom should we rename DynamicSeriesNode => CanvasPlotNode?  Should we rename DynamicSeries => XYPlotData or XYDataModel or XYDataSeries?

UPDATE: There is a good answer in https://github.com/phetsims/griddle/issues/74#issue-734777503, I recommend we continue in that issue.
