### ISSUE TITLE
griddle lacks "plot" abstraction

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/griddle#74]
In https://github.com/phetsims/griddle/issues/71#issuecomment-697106346, I discussed terminology:

> ... A chart is the grid + axes + plots --- the whole package.
> 
> A plot is what's drawn on the chart - the rendering of one data set (e.g DynamicSeries).
> 
> A chart should be able to draw multiple plots 

And I noted that griddle currently lacks a "plot":

> griddle is currently missing the XYPlotNode piece of this puzzle. Each DynamicsSeries should be rendered by an XYPlotNode on the XYChartNode.

Issues:

* XYCursorChartNode can only draw one type of plot, as indicated by `plotStyle`.  It should not care about the plot style, and should defer to XYPlotNode for how to render data.

* Documentation for DynamicSeriesNode says "This class renders DynamicSeries data in a XYChartNode and is tightly coupled with XYChartNode".   It's not clear why they DynamicSeriesNode is tightly couple to XYChartNode, but if that's true, it's a big red flag for the design.

* DynamicSeriesNode might be the closest thing that griddle has to XYPlotNode.  Start by renaming DynamicSeries and DynamicSeriesNode to XYSeries and XYPlotNode respectively, and you'll probably be a step closer to the desired abstractions.

**Comment by samreid** [comment]
As far as I can tell, this is fixed in bamboo.  @pixelzoom can this issue be closed?

**Comment by pixelzoom** [comment]
Yes, LinePlot meets this need. Closing.
