### ISSUE TITLE
Missing or incorrect visibility annotations in griddle

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/griddle#75]
- [x] XYChartNode:

```js
156    this.gridNode = new GridNode( this.chartWidth, this.chartHeight, gridNodeOptions );
```

- [ ] XYCursorChartNode.ChartCursor 

```js
300    this.chart = chart;
301    this.modelViewTransformProperty = modelViewTransformProperty;
307    this.includeDragCue = options.includeDragCue;
```

`this.chart` and `this.modelViewTransformProperty` also appear to be unused outside of the constructor. Do they really need to be properties?

- [ ] PointStyledVector2

Is `this.pointStyle` mutable, or should it be `@public (read-only)`?

```js
24 // @public {PointStyle}
25 this.pointStyle = pointStyle;
```

**Comment by samreid** [comment]
Fixed, closing.
