### ISSUE TITLE
BarChartNode does not support XY data sets

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/griddle#76]
In Fourier, we need to plot (x,y) data as a bar chart:

<img width="738" alt="screenshot_647" src="https://user-images.githubusercontent.com/3046552/97917621-f7902280-1d11-11eb-845c-5f4fb96078d1.png">

A couple of problems that make BarChartNode unusable for Fourier:

* BarChartNode does not support model-view transform for the x axis. XYChartNode has a modelViewTransformProperty, which handles (x,y) transforms.  But BarChartNode has no modelViewTransformProperty.  It has `scaleProperty`, which is applied to the y axis.  `barSpacing` sets the x spacing between bars.   This does not work for Fourier -- we have an XY data set, and an x transform is required.

* BarChartNode supports a fixed number of bars. The model passed to BarChartNode is:

```js
   * @param {Array.<Object>} bars - Entries of the format:
   *   {
   *     entries: {Array.<{ property: {Property.<number>}, color: {paint} }>}
   *     [labelString]: {string} formatted for RichText
   *     [labelColor]: {PaintDef} if provided, sets color of the bar label, otherwise label match color of bar
   *     [labelNode]: {node} displayed below the label string if the label string exist
   *     [offScaleArrowFill]: {paint} - If provided, allows bar-specific arrow fills (that are different than the color)
   *   }
```

And `bars` is immutable after constructor.  So while each bar has a dynamic value (via a Property) this API assumes that there are a fixed number of bars.  That is not the case in Fourier; there is an XY data set that changes based on the spacing between Fourier components. 

So... BarChartNode is not usable for plotting XY data.  We'll see what I come up with in Fourier, an whether it can be generalized.  But I'm going to start by doing something specific to Fourier.

@ariel-phet FYI.

**Comment by samreid** [comment]
This should be implemented on top of XYChartNode (or a related abstraction), not BarChartNode, since this is more of a 2D data set than a categorical bar chart data set.

**Comment by samreid** [comment]
This support was added to bamboo, and looks like this in the demo:

![image](https://user-images.githubusercontent.com/679486/99866148-16911000-2b6c-11eb-9562-c18b5e7427c4.png)

Closing.
