### ISSUE TITLE
griddle doesn't have a consistent approach to model-view transform and ranges

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/griddle#77]
BarChartNode has no model-view transform, and no model-view transform support for the x axis.  It has constructor param `yRangeProperty` (in model coordinates) and `barSpacing` (in view coordinates?) and BarNode has option `scaleProperty` (to scale y model to view?).  This is all very odd and should have been addressed with a standard ModelViewTransform2.

XYChartNode has option `{Property.<ModelViewTransform2>} modelViewTransformProperty`, which is a dynamic model-view transform. But it also has options `defaultModelXRange` and `defaultModelYRange`, which are very odd, and not used where I'd expect them to be used -- for example, in CCK:DC where the chart is zoomable. 

SeismographNode extends XYChartNode, and adds its own way of deals with range. It has options `verticalRangeProperty` and `horizontalRangeProperty`.  Why are these specific to SeismographNode? What are they not in XYChartNode?  What happens if I try to use XYChartNode's features with SeismographNode's features? 

So... There's no consistent approach here.  I'm guessing that all of the above is symptomatic of (1) classes being migrated to griddle from sims, (2) the lack of an overall design for griddle that helps guide how migrated classes are generalized.   This needs to be cleaned up before it is propagated to more sims, and certainly before it's usable in Fourier. 

Assigning to @ariel-phet for prioritization and assignment.

**Comment by samreid** [comment]
As far as I can tell, this problem is corrected in bamboo.  @pixelzoom can this issue be closed?

**Comment by pixelzoom** [comment]
Yes, addressed in bamboo.  No need to spend time on deprecated (griddle) code. Closing.
