### ISSUE TITLE
missing visibility annotation for the GridNode

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/griddle#79]
XYChartNode is missing visibility annotation for the GridNode that it creates:

```js
    this.gridNode = new GridNode( this.chartWidth, this.chartHeight, gridNodeOptions );
```

Added by @jessegreenberg in f4bdbc34455d096f1348fe6542c263865ec292e3, but @samreid is actively working on griddle. So I'll assign to both.

**Comment by samreid** [comment]
Fixed, closing.
