### ISSUE TITLE
XYChartNode should be able to render axis labels.

### ISSUE THREAD

**Issue by samreid** [phetsims/griddle#80]
In https://github.com/phetsims/fourier-making-waves/issues/8 @pixelzoom suggested that XYChartNode should be able to render axis labels.  The design for https://github.com/phetsims/fourier-making-waves/issues/8 is under consideration, and this feature may not be used there.

What should the API be for this feature?  How would I tell a chart to show major grid labels on the left, and an axis label on the right?  How much of this feature should be hard-coded in XYChartNode vs making it easy to add "decorations" to it?

**Comment by pixelzoom** [comment]
In reference to the x-axis label on this chart:

![image](https://user-images.githubusercontent.com/679486/98632344-92719980-22dc-11eb-8268-b02c49f3bf79.png)

In https://github.com/phetsims/fourier-making-waves/issues/8#issuecomment-724860566, @samreid said:
> This seemed an unconventional way to label a chart (at least I couldn't think of any other occurrences like that). But if we think this style will be widely used, let's add it to XYChartNode.

In https://github.com/phetsims/fourier-making-waves/issues/8#issuecomment-724865487, I asked:
> What's unconventional about it?

Should I not expect to be able to implement the XY charts in the graphing-lines suite using XYChartNode?  Should I have to handle adding the axis labels as decorations?  E.g.:

<img width="605" alt="screenshot_673" src="https://user-images.githubusercontent.com/3046552/98756280-76770200-2387-11eb-9491-7154557c56d9.png">

**Comment by samreid** [comment]
This may be addressed in https://github.com/phetsims/griddle/issues/86

**Comment by samreid** [comment]
This is addressed in bamboo, @pixelzoom can this issue be closed?

**Comment by pixelzoom** [comment]
Yes, addressed by bamboo. Closing.
