### ISSUE TITLE
Fix terminology for tick marks and tick labels in XYChartNode

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/griddle#83]
In https://github.com/phetsims/griddle/issues/81, I said:
> "labels along the grid lines" are typically called "tick mark labels", or more tersely "tick labels".

This unfortunate "grid lines" terminology extends beyond options. 

```js
    this.showVerticalGridLabels = options.showVerticalGridLabels;
    this.showHorizontalGridLabels = options.showHorizontalGridLabels;
...
    this.verticalGridLabelLayer = new Node();
    this.horizontalGridLabelLayer = new Node();
```

Recommended to fix terminology to refer to tick marks and tick labels throughout.

**Comment by samreid** [comment]
As far as I can tell, this is solved by bamboo.  @pixelzoom can this issue be closed?

**Comment by pixelzoom** [comment]
Yes, addressed by bamboo. No need to address in deprecated (griddle) code. Closing.
