### ISSUE TITLE
XYChartNode support for axes, tick marks, and tick labels 

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/griddle#84]
Here's XYChartNode in the griddle demo:

<img width="561" alt="screenshot_671" src="https://user-images.githubusercontent.com/3046552/98755435-c5239c80-2385-11eb-8bf2-74cc3376bca7.png">

Where are the axes, typically drawn through (0,0) ?

Also note the absence of tick marks. There are tick labels, but no tick marks. That might be a (non-default) option, but I doubt that this is acceptable for PhET sims. Tick marks should be aligned with tick labels.  For example in graphing-lines:

<img width="557" alt="screenshot_672" src="https://user-images.githubusercontent.com/3046552/98755526-fd2adf80-2385-11eb-836f-a26d9d3c9111.png">

Finally, there's a problem with the placement of tick labels.  XYChartNode puts its tick labels around the border of its background Rectangle, as you can see in the demo.    Putting them around the border might be an option, but as shown in the graphing-lines example above, that is not generally acceptable -- tick marks and labels are more typically on the axes.

**Comment by pixelzoom** [comment]
From https://github.com/phetsims/fourier-making-waves/issues/8#issuecomment-726395536:

* Tick labels need to support different formats. Different sims have different formatting needs, and options `verticalGridLabelNumberOfDecimalPlaces` and `horizontalGridLabelNumberOfDecimalPlaces` are not sufficient.

* Charts (in general) need to support axes and tick marks.

**Comment by samreid** [comment]
In https://github.com/phetsims/griddle/issues/86 we are pursuing a paradigm that makes the axes and tick marks, tick labels more customizable.

**Comment by samreid** [comment]
As far as I can tell, bamboo supports all of the features requested in this issue.  @pixelzoom can this be closed?

**Comment by pixelzoom** [comment]
Yes, addressed by bamboo. Closing.
