### ISSUE TITLE
provide features needed by least-squares-regression

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/griddle#9]
See https://github.com/phetsims/least-squares-regression/issues/22#issuecomment-76032235

**Comment by samreid** [comment]
I think bamboo provides most or all of the requested features.  Any missing features would be hopefully easy to add.  I don't see an immediate need to port least-squares-regression to bamboo, but that will be an option for the future if other changes are required in that area.  I recommend closing this issue.
