### ISSUE TITLE
Should this radius be passed to Rectangular Button?

### ISSUE THREAD

**Issue by samreid** [phetsims/griddle#91]
From https://github.com/phetsims/griddle/issues/46

> - [ ] @jessegreenberg while working on https://github.com/phetsims/sun/issues/657, I found that this line here passes a radius to a RectangularButton. Can we remove it? It was added in b0344ba89169855a8b5a97e5f46184719ea2e5b0, or at least moved around. I think it can be removed.

**Comment by jessegreenberg** [comment]
I took a look at the commit https://github.com/phetsims/griddle/commit/b0344ba89169855a8b5a97e5f46184719ea2e5b0, I think you are referring to the `zoomButtonOptions`:

```
      const zoomButtonOptions = {
        left: this.chartPanel.right + 5,
        baseColor: '#97c7fa',
        radius: 6,
        xMargin: 5,
        yMargin: 3
      };
```

In this case, `radius` is a ZoomButton option for the magnifying glass icon, so I think it needs to stay.

**Comment by zepumph** [comment]
It would by my opinion to rename this option so that this confusion doesn't happen again. What about `zoomRadius`?

**Comment by jessegreenberg** [comment]
Sure, I could see that. There other options with `magnifyingGlass` as the prefix so maybe `magnifyingGlassRadius`. This is a scenery-phet component though used in many places outside of griddle. I am going to move the recommendation there.

**Comment by jessegreenberg** [comment]
I made https://github.com/phetsims/scenery-phet/issues/645
